# Generated by Django 5.1.3 on 2024-11-25 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0002_bank_transaction_additional_fields_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_hash',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
