# Generated by Django 5.1.3 on 2024-11-25 07:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0003_alter_transaction_transaction_hash'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holder_name', models.CharField(max_length=255, null=True)),
                ('account_number', models.CharField(max_length=50, unique=True)),
                ('address', models.TextField(null=True)),
                ('opening_date', models.CharField(max_length=50, null=True)),
                ('account_status', models.CharField(max_length=50, null=True)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('nominee_status', models.CharField(max_length=100, null=True)),
                ('branch', models.CharField(max_length=100, null=True)),
                ('ifsc_code', models.CharField(max_length=20, null=True)),
                ('account_type', models.CharField(max_length=50, null=True)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='account',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='account',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='account',
            name='user',
        ),
        migrations.RemoveField(
            model_name='statement',
            name='account',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='statement',
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-date']},
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='bankapp_tra_account_2fe695_idx',
        ),
        migrations.RemoveIndex(
            model_name='transaction',
            name='bankapp_tra_transac_86ee5f_idx',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='additional_fields',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_hash',
        ),
        migrations.AddField(
            model_name='transaction',
            name='additional_info',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='bankapp.accountinfo'),
        ),
        migrations.DeleteModel(
            name='Bank',
        ),
        migrations.DeleteModel(
            name='Statement',
        ),
        migrations.DeleteModel(
            name='Account',
        ),
    ]
