# Generated by Django 5.1.3 on 2024-11-25 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0004_accountinfo_alter_account_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='cheque_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='value_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('Dr', 'Debit'), ('Cr', 'Credit')], max_length=10),
        ),
    ]
