# Generated by Django 5.1.3 on 2024-11-25 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0005_transaction_cheque_no_transaction_value_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['txn_date']},
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='date',
            new_name='txn_date',
        ),
    ]
