# Generated by Django 5.1.3 on 2024-11-25 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0007_remove_transaction_amount_transaction_deposits_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='additional_info',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_type',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='txn_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='value_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
