# Generated by Django 5.1.3 on 2024-12-02 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0011_remove_transaction_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankstatement',
            name='account_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bankstatement',
            name='transactions',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
