# Generated by Django 5.1.3 on 2024-12-02 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0012_bankstatement_account_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankstatement',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='bankstatement',
            name='transactions',
        ),
        migrations.AlterField(
            model_name='bankstatement',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='bankstatement',
            name='type',
            field=models.CharField(blank=True, choices=[('CR', 'Credit'), ('DR', 'Debit')], max_length=2, null=True),
        ),
    ]
