# Generated by Django 5.1.3 on 2024-12-02 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0013_remove_bankstatement_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankstatement',
            name='account_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bankstatement',
            name='type',
            field=models.CharField(blank=True, choices=[('CR', 'Credit'), ('DR', 'Debit')], max_length=50, null=True),
        ),
    ]
