# Generated by Django 5.1.3 on 2024-12-05 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0015_remove_bankstatement_account_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankstatement',
            name='account_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
