# Generated by Django 5.1.3 on 2024-12-11 06:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0017_remove_bankstatement_account_number_accountdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankstatement',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='bankstatement',
            name='statement_type',
        ),
        migrations.AddField(
            model_name='accountdetails',
            name='account_holder_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bankstatement',
            name='account_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='bankapp.accountdetails'),
        ),
        migrations.AlterField(
            model_name='accountdetails',
            name='account_number',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Account number must be 10-16 digits', regex='^\\d{10,16}$')]),
        ),
        migrations.AlterField(
            model_name='bank',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='bankstatement',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='bankstatement',
            name='description',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bankstatement',
            name='type',
            field=models.CharField(choices=[('CR', 'Credit'), ('DR', 'Debit')], default='DR', max_length=2),
        ),
        migrations.AlterField(
            model_name='statementtype',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='accountdetails',
            unique_together={('bank', 'account_number')},
        ),
    ]
