# Generated by Django 5.1.3 on 2024-12-11 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0018_remove_bankstatement_bank_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='statementtype',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
