# Generated by Django 5.1.3 on 2024-12-11 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0019_alter_bank_name_alter_statementtype_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='accountdetails',
            unique_together=set(),
        ),
    ]
