# Generated by Django 5.1.3 on 2024-12-11 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0020_alter_accountdetails_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankstatement',
            name='type',
            field=models.CharField(choices=[('CR', 'Credit'), ('DR', 'Debit')], default='DR', max_length=50),
        ),
    ]
