# Generated by Django 5.1.3 on 2024-12-14 13:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0021_alter_bankstatement_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountdetails',
            name='account_number',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='Account number must be 10-16 digits', regex='^\\d{10,16}$')]),
        ),
    ]
